version: '3'
services:
    nodeapp:
        build:
            context: ./Nodeithil
        container_name: nodeithil
        hostname: nodeithil
        ports:
            - "1337:1337"
        networks:
            - one-net
        depends_on:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"
        networks:
            - one-net
    nginx:
        build:
            context: ./nginx
        container_name: nginx
        hostname: nginx
        ports:
            - "8980:80"
        depends_on:
            - nodeapp
        networks:
            - one-net

networks:
    one-net:
        external: true
